name: Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib

    - name: Setup
      run: |
        mkdir build
        cd build/
        cmake .. -DPICO_SDK_FETCH_FROM_GIT=on

    - name: Build
      run: |
        cd build/
        make -j
